# config file
problem:
    type: classification
    loss: Logistic
    regularizer: L2
    reg_parameter: 0.0001
    dataset_names:
        - dummy
    dataset_path_folder: datasets
    
results: 
    output_path: output/dummy
    xp_name: dummy
    measure_time: False
    save_data: True
    save_plot: True
    do_we_plot: True
    verbose: True
    log_file: log.txt
    
    dpi: 50
    plot_threshold: 1.0e-12
    subopt: True
    records_to_plot: # list of Records names
        - gradient_norm
        - function_value

solvers_parameters: # general parameters applied to all solvers. can be overwritten by specific solver parameters below
    nb_repetition: 2
    nb_epochs: 50
    tolerance: 1e-10
    initialization: zeros
    distribution: uniform
    
# list of solvers and their specific parameters. can have duplicates but name_result must differ
solvers: 
    - FUVAL:
        s_type: zeros
        stepsize_type: constant
        grid_search:
            stepsize_factor:
                min: 0.1
                max: 20.0
                number: 20
                scale: log

    - SGD:
        stepsize_type: constant
        grid_search:
            stepsize_factor:
                min: 0.0001
                max: 1.0
                number: 20
                scale: log
            

    